easy_admin:
    site_name: 'App Admin'

    design:
        brand_color: '#1976D2'
        assets:
            css:
                - 'build/admin.css'
            js:
                - 'build/runtime.js'
                - 'build/admin.js'

    formats:
        date: 'Y-m-d'
        time: 'H:i:s'
        datetime: 'Y-m-d H:i:s'
