vich_uploader:
    db_driver: orm

    mappings:
        default_mapping:
            uri_prefix: /uploads
            upload_destination: '%kernel.project_dir%/public/uploads'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            directory_namer:
                service: Vich\UploaderBundle\Naming\SubdirDirectoryNamer
                options:
                    chars_per_dir: 2
                    dirs: 2
